app/mapdrop/blueprints/main/__init__.py
from .main import main

app/mapdrop/blueprints/main/main.py
import os
import re
import json

from slugify import slugify
from flask import Blueprint, Response, render_template, abort, render_template_string, request, jsonify, redirect, url_for, current_app
from shapely.geometry import mapping, shape
from functools import wraps
from shapely.wkt import loads
from mapdrop import redis_store

from ...mapdropfile import MapdropFile

main = Blueprint('main', __name__, template_folder='templates', url_prefix='/')


class APIException(Exception):
    status_code = 400

    def __init__(self, message, status_code=None, payload=None):
        Exception.__init__(self)
        self.message = message
        if status_code is not None:
            self.status_code = status_code
        self.payload = payload

    def to_dict(self):
        rv = dict(self.payload or ())
        rv['message'] = self.message
        rv['status_code'] = self.status_code
        rv['payload'] = None
        return rv

@main.errorhandler(APIException)
def handle_api_error(error):
    response = jsonify(error.to_dict())
    response.status_code = error.status_code
    return response



def validate_filename(filename):
    """
    Validate a filename. Must be one character long, and can only contain
    a-z A-Z 0-9 and characters . - _.
    """
    if len(filename) == 0:
        return False
    exp = re.compile(r'[^a-zA-Z0-9\.\-\_]')
    return not bool(exp.search(filename))

def validate_directory(directory):
    exp = re.compile(r'[^a-zA-Z0-9\.\-\_\/]')
    return not bool(exp.search(directory))

def path_validate(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        path = kwargs.get("path", "")
        print("args=")
        print(args)


        print("checking path {}".format(path))
        directory, filename = os.path.split(path)
        print("directory={} filename={}".format(directory, filename))

        if filename == '':
            # Working with directory
            if validate_directory(directory):
                kwargs.update({'filename':filename, 'directory':directory, 'path':path})
                return f(*args, **kwargs)
            else:
                raise APIException("Invalid directory path", status_code=400)

        else:
            # Working with a file
            if validate_directory(directory) and validate_filename(filename):
                kwargs.update({'filename':filename, 'directory':directory, 'path':path})
                return f(*args, **kwargs)
            else:
                raise APIException("Invalid file path", status_code=400)
    return decorated_function

def path_exists_or_404(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        path = kwargs.get("path", "")
        directory, filename = os.path.split(path)
        fullpath = os.path.join(current_app.config.get("MAPDROP_DATA"), directory, filename)
        print(fullpath)
        kwargs.update({'fullpath':fullpath})
        if os.path.isfile(fullpath) or os.path.isdir(fullpath):
            return f(*args, **kwargs)
        else:
            raise APIException("Path not found", status_code=404)
    return decorated_function

@main.route('/', methods=['GET'])
@main.route('/<path:path>', methods=['GET'])
@path_validate
@path_exists_or_404
def info(*args, **kwargs):
    """
    Preview 
    """
    path = kwargs.get("path")
    mapdrop_version = current_app.config['MAPDROP_VERSION']

    path_components = []

    path_split = path.split("/")
    for n, comp in enumerate(path_split):
        path_item = "/".join(path_split[:n+1])
        if n < (len(path_split)-1):
            path_item += '/'
        path_components.append({'name':comp, 'path': path_item})

    if kwargs.get("filename") == '':
        # Directory view
        contents = []
        fullpath = os.path.join(current_app.config.get("MAPDROP_DATA"), path)
        for item in os.listdir(fullpath):
            item_localpath = os.path.join(path, item)
            item_path = os.path.join(fullpath, item)
            if os.path.isfile(item_path):
                contents.append({'type':'file','name':item, 'info':'', 'path':item_localpath, 'icon':'far fa-map'})
            if os.path.isdir(item_path):
                info = "{}".format(len(os.listdir(os.path.join(fullpath, item))))
                contents.append({'type':'dir','name':item+'/', 'info':info, 'path':item_localpath+'/', 'icon':'far fa-folder'})
        num_items = len(contents)
        return render_template("main/directory.html", **locals())
    else:
        # File view
        path = kwargs.get("path")
        mf = MapdropFile(path)
        return render_template("main/info.html", **locals())

# Views related to derived data from individial files (tiles, previews, etc) below
@main.route('/<path:path>~/tiles/<int:z>/<int:x>/<int:y>.<string:format>', methods=['GET'])
@path_validate
@path_exists_or_404
def tile(path, z, x, y, format, **kwargs):
    fullpath = os.path.join(current_app.config.get("MAPDROP_DATA"), path)
    mf = MapdropFile(fullpath)
    return mf.ds.tile(z, x, y, format=format, request_args=request.args)

@main.route('/<path:path>~/metadata/metadata.json', methods=['GET'])
@path_validate
@path_exists_or_404
def metadata(path, **kwargs):
    mf = MapdropFile(path)
    return jsonify(mf.metadata)

@main.route('/<path:path>~/metadata/extent.<string:format>', methods=['GET'])
@path_validate
@path_exists_or_404
def metadata_extent(path, format, **kwargs):
    mf = MapdropFile(path)
    geom = loads(mf.metadata.get("extent"))
    if format == 'json':
        return jsonify(mapping(geom))
    if format == 'wkt':
        return Response(geom.wkt, mimetype='text/plain')

@main.route('/<path:path>~/metadata/crs.<string:format>', methods=['GET'])
@path_validate
@path_exists_or_404
def metadata_crs(path, format, **kwargs):
    mf = MapdropFile(path)
    if format == 'wkt':
        return Response(mf.metadata.get("crs"), mimetype='text/plain')


@main.route('/<path:path>~/raw', methods=['GET'])
@path_validate
@path_exists_or_404
def raw(path, **kwargs):
    #mf = MapdropFile(kwargs.get("fullpath"))
    #return jsonify(mf.ds.metadata)
    return "RAW file"

@main.route('/<path:path>~/view', methods=['GET'])
@path_validate
@path_exists_or_404
def view(path, **kwargs):

    tilelayer_url = '/'+path+'~/tiles/{z}/{x}/{y}.png'
    return render_template("main/preview.html", **locals())



@main.route('/<path:path>~/<path:subpath>')
@path_validate
def catchall(*args, **kwargs):
    """
    Catch-all route for a path followed by a ~ that is not matched by 
    any valid views defined above.
    """
    return 'Invalid subpath', 404

@main.route('/<path:path>', methods=['PUT','POST'])
@path_validate
def put(path, **kwargs):
    directory, filename = os.path.split(path)
    fullpath = os.path.join(current_app.config.get("MAPDROP_DATA"), directory, filename)
    fulldirectory = os.path.join(current_app.config.get("MAPDROP_DATA"), directory)

    if os.path.isfile(fullpath):
        raise APIException("File already exists. Delete old one first", status_code=400)
    else:
        if not os.path.exists(fulldirectory):
            try: 
                os.makedirs(fulldirectory)
            except: 
                raise APIException("Could not create directory.", status_code=500)
        with open(fullpath, 'wb') as f:
            f.write(request.data)
        return 'PUT {}'.format(path), 200

app/mapdrop/blueprints/main/templates/main/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/css/style.css">
    {% block headjs %}{% endblock %}
    {% block headcss %}{% endblock %}
</head>
<body>
    {% block header %}
    {% endblock %}

    {% block content %}
    {% endblock %}

    {% block footer %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    {% block footjs %}{% endblock %}
    {% block footcss %}{% endblock %}

</body>
</html>

app/mapdrop/blueprints/main/templates/main/directory.html
{% extends "main/base.html" %}

{% block header %}
    <div style="background-color:#e5e5e5;margin-bottom:15px;padding:10px;">
        <div class="container">
            <div class="row align-items-center" style="height:60px;">
                <div class="col-sm-10">
                    <h1>
                        <a href="{{ url_for('main.info', path='') }}"><i class="far fa-fw fa-folder" style=""></i></a>{% for comp in path_components %}/<a href="{{url_for('main.info',path=comp.path)}}">{{comp.name}}</a>{% endfor %}
                    </h1>
                </div>
                <div class="col-sm-2 text-right">
                    <span class="mapdrop-version"><a href="https://www.github.com/kokoalberti/mapdrop">Mapdrop {{mapdrop_version}}</a></span>
                </div>
            </div>   
        </div>
    </div>  
{% endblock %}

{% block content %}
<div class="container">
    <table class='table table-sm directory-table'>
        <tr>
            <th colspan="2">
                {% if num_items == 0 %}
                    No items found
                {% endif %}
                {% if num_items == 1 %}
                    Found 1 item
                {% endif %}
                {% if num_items > 1 %}
                    Found {{num_items}} items
                {% endif %}
            </th>
        </tr>
        {% for item in contents %}
            <tr>
                <td><i class="{{item.icon}} fa-fw" style="color:#aaa;"></i></td>
                <td style="width:100%;">
                    <a href="{{ url_for('main.info', path=item.path) }}" style="margin-left:5px;">{{item.name}}{% if item.info %}<span class="item-info">({{item.info}})</span>{% endif %}</a>
                </td>
            </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

app/mapdrop/blueprints/main/templates/main/info.html
{% extends "main/base.html" %}    

{% block title %}
    {{mf.path}} - Info
{% endblock %}

{% block headcss %}
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.3/dist/leaflet.css"/>
{% endblock %}

{% block headjs %}
    <script src="https://unpkg.com/leaflet@1.0.3/dist/leaflet.js"></script>
{% endblock %}

{% block header %}
    <div style="background-color:#e5e5e5;margin-bottom:15px;padding:10px;">
        <div class="container">
            <div class="row align-items-center" style="height:60px;">
                <div class="col">
                    <h1><!--<i class="fa-fw far fa-file"></i>-->
                    <a href="{{ url_for('main.info', path='') }}"><i class="far fa-fw fa-folder" style=""></i></a>{% for comp in path_components %}/<a href="{{url_for('main.info',path=comp.path)}}">{{comp.name}}</a>{% endfor %}
                    
                    </h1>
                </div>
                <div class="col text-right">
                    <!--<a class="action" href="{{path}}~/raw"><i class="fas fa-file-download"></i></a>-->
                </div>
            </div>   
        </div>
    </div>  
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <h3>Metadata</h3>
                <table class='table table-sm'>
                    <tr><td><strong>Path</strong></td><td><code>{{mf.path}}</code></td></tr>
                    <tr><td><strong>Type</strong></td><td>{{ mf.metadata['type'] }}</td></tr>
                    <tr><td><strong>Metadata</strong></td><td><code><a href="{{url_for('main.metadata', path=path)}}">~/metadata/metadata.json</a></code>
                    </td></tr>
                    <tr><td><strong>CRS</strong></td><td><code><a href="{{url_for('main.metadata_crs', path=path, format='wkt')}}">~/metadata/crs.wkt</a></code>
                    </td></tr>
                    <tr><td><strong>EPSG</strong></td><td>                        {% if mf.metadata['epsg'] %}
                            {{mf.metadata['epsg']}}
                        {% endif %}</td></tr>
                    <tr><td><strong>Extent</strong></td><td><code><a href="{{url_for('main.metadata_extent', path=path, format='json')}}">~/metadata/extent.json</a></code> or <code><a href="{{url_for('main.metadata_extent', path=path, format='wkt')}}">~/metadata/extent.wkt</a></code></td></tr>

                </table>
                <h3>Preview</h3>
                <div id="map-wrapper">
                    <div id="map"></div>
                </div>
                <h3>Layers</h3>
                <table class='table table-sm'>
                    <tr><th>Name</th><th>Datatype</th></tr>
                {% for layer in mf.metadata['layers'] %}
                    <tr><td>{{layer.name}}</td><td>{{layer.datatype}}</td></tr>
                {% endfor %}
                </table>
                <h3>Endpoints</h3>
                <h4>Tiles</h4>
                <p>
                    Tiles can be viewed at <code>/{{path}}~/tiles/{z}/{x}/{y}.png</code>
                </p>
                <h4>View</h4>
                <p>Full-screen map view available at <code><a href="/{{path}}~/view">/{{path}}~/view</a></code>.
                <h4>Raw</h4>
                <p>Raw data downloadable (HTTP range requests also) via <code><a href="/{{path}}~/view">/{{path}}~/raw</a></code>.
                <h3>Actions</h3>

            </div>
        </div>

    </div>

{% endblock %}

{% block footjs %}
    <script type="text/javascript">
        var options = {
            attributionControl: false
        }

        var map = L.map('map', options);

        $.getJSON("/{{ path }}~/metadata/extent.json", function(data) {
            var osm = L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(map);
            var path = L.tileLayer('/{{ path }}~/tiles/{z}/{x}/{y}.png').addTo(map); 
            var extent = L.geoJson(data, {"fillOpacity": 0}).addTo(map);
            map.fitBounds(extent.getBounds());
        });
    </script>
{% endblock %}

app/mapdrop/blueprints/main/templates/main/preview.html
<!DOCTYPE html>
<html>
<head>
    <title>Mapdrop Preview</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.3/dist/leaflet.css"/>
    <script src="https://unpkg.com/leaflet@1.0.3/dist/leaflet.js"></script>
    </script>
    <style type="text/css">
        body {
            margin:0;
        }
        div#map-wrapper {
            display: flex;    
            width:100vw;
            height:100vh;
        }
        div#map-wrapper div {
            flex-basis: 100%;
        }
    </style>
</head>
<body>
    <div id="map-wrapper">
        <div id="map"></div>
    </div>
    <script type="text/javascript">
        // Default options we'll use for both maps. Se the center of the map,
        // default zoom levels, and other Leaflet map options here.
        var options = {
            center: [52.086331, 4.295077],
            zoom: 12,
            attributionControl: false
        }

        // Create the left and the right map in their respective containers
        var map = L.map('map', options);

        // Add our tiles to the left map and an openstreetmap layer to the 
        // right map
        
        L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(map);
        L.tileLayer('{{ tilelayer_url | safe }}').addTo(map); 
    </script>
</body>
</html>